import React from 'react';
import {
  View,
  Text,
  ScrollView,
  Image,
  TouchableOpacity,
  StyleSheet,
  Linking,
} from 'react-native';
import { NativeStackNavigationProp } from '@react-navigation/native-stack';
import { RouteProp } from '@react-navigation/native';
import { RootStackParamList } from '../types';
import { BreedCard } from '../components/BreedCard';

type ResultScreenNavigationProp = NativeStackNavigationProp<
  RootStackParamList,
  'Result'
>;
type ResultScreenRouteProp = RouteProp<RootStackParamList, 'Result'>;

interface ResultScreenProps {
  navigation: ResultScreenNavigationProp;
  route: ResultScreenRouteProp;
}

export const ResultScreen: React.FC<ResultScreenProps> = ({ navigation, route }) => {
  const { predictions, breedInfo, imageUri } = route.params;

  const topPrediction = predictions[0];
  const otherPredictions = predictions.slice(1);

  const handleOpenAKC = () => {
    if (breedInfo?.akc_url) {
      Linking.openURL(breedInfo.akc_url).catch((err) =>
        console.error('Failed to open URL:', err)
      );
    }
  };

  const handleTryAgain = () => {
    navigation.navigate('Home');
  };

  return (
    <View style={styles.container}>
      <ScrollView style={styles.scrollView}>
        {/* Image Preview */}
        <View style={styles.imageContainer}>
          <Image source={{ uri: imageUri }} style={styles.image} resizeMode="cover" />
        </View>

        {/* Results Header */}
        <View style={styles.headerContainer}>
          <Text style={styles.headerTitle}>Analysis Complete! 🎉</Text>
          <Text style={styles.headerSubtitle}>
            Here are the top {predictions.length} breed predictions:
          </Text>
        </View>

        {/* Top Prediction */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Most Likely Breed</Text>
          <BreedCard
            prediction={topPrediction}
            breedInfo={breedInfo}
            isTopPrediction={true}
          />
          
          {breedInfo?.akc_url && (
            <TouchableOpacity
              style={styles.akcButton}
              onPress={handleOpenAKC}
            >
              <Text style={styles.akcButtonText}>
                View on American Kennel Club →
              </Text>
            </TouchableOpacity>
          )}
        </View>

        {/* Other Predictions */}
        {otherPredictions.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Other Possibilities</Text>
            {otherPredictions.map((prediction, index) => (
              <BreedCard key={index} prediction={prediction} />
            ))}
          </View>
        )}

        {/* Disclaimer */}
        <View style={styles.disclaimer}>
          <Text style={styles.disclaimerText}>
            ℹ️ These predictions are generated by AI and may not be 100% accurate.
            For professional breed identification, consult a veterinarian.
          </Text>
        </View>

        {/* Bottom Spacing */}
        <View style={{ height: 100 }} />
      </ScrollView>

      {/* Bottom Action Bar */}
      <View style={styles.bottomBar}>
        <TouchableOpacity
          style={styles.actionButton}
          onPress={handleTryAgain}
        >
          <Text style={styles.actionButtonText}>Try Another Photo</Text>
        </TouchableOpacity>
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f9fafb',
  },
  scrollView: {
    flex: 1,
  },
  imageContainer: {
    width: '100%',
    height: 300,
    backgroundColor: '#000',
  },
  image: {
    width: '100%',
    height: '100%',
  },
  headerContainer: {
    padding: 20,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#111827',
    marginBottom: 8,
  },
  headerSubtitle: {
    fontSize: 16,
    color: '#6b7280',
  },
  section: {
    padding: 16,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#111827',
    marginBottom: 12,
  },
  akcButton: {
    marginTop: 12,
    padding: 16,
    backgroundColor: '#1e40af',
    borderRadius: 12,
    alignItems: 'center',
  },
  akcButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
  },
  disclaimer: {
    margin: 16,
    padding: 16,
    backgroundColor: '#fef3c7',
    borderRadius: 12,
    borderLeftWidth: 4,
    borderLeftColor: '#f59e0b',
  },
  disclaimerText: {
    fontSize: 14,
    color: '#92400e',
    lineHeight: 20,
  },
  bottomBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 5,
  },
  actionButton: {
    backgroundColor: '#3b82f6',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  actionButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
  },
});
